object FormBaseMaster: TFormBaseMaster
  Left = 265
  Top = 131
  Caption = 'FormBaseMaster'
  ClientHeight = 462
  ClientWidth = 854
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Verdana'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  ShowHint = True
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 13
end
